using System.Text.Json;
using CsiRadar.Backend.Application.Processing.Dsp;
using Xunit;

namespace CsiRadar.Backend.Tests;

/// <summary>
/// Golden cross-language parity harness (the mandatory Phase 2 gate — train/serve
/// identity is the #1 project invariant).
///
/// The backend is the source of truth: this test computes each DSP stage from a fixed,
/// fully-deterministic integer input and DUMPS the inputs + outputs to
/// <c>tools/parity/dsp_golden.json</c>. The Python twin
/// (<c>wifi-csi-ml/tests/test_dsp_parity.py</c> + <c>src/dsp_twin.py</c>) reads that
/// same file, recomputes from the identical integer inputs, and asserts it reproduces
/// the outputs within a float32 tolerance. Because the inputs are integers, there is
/// no float-input divergence — only the transform is under test.
///
/// "Bit-for-bit" is realised as "within float32 numerical noise": amplitude is exact,
/// while phase (atan2) and STFT (cos/sin) carry sub-ULP libm differences that are
/// numerically irrelevant. The tolerance is tight enough to catch any structural
/// divergence (wrong unwrap, wrong detrend, wrong window/hop, wrong axis/bin count).
/// </summary>
public class DspGoldenParityTests
{
    // Fixed, deterministic inputs — mirrored exactly in the Python twin's regeneration.
    private const int Subcarriers = 64;
    private const int SeriesLength = 128;

    private static sbyte[] BuildRawIq()
    {
        var raw = new sbyte[2 * Subcarriers];
        for (int k = 0; k < Subcarriers; k++)
        {
            raw[2 * k] = (sbyte)(((k * 7 + 3) % 61) - 30);      // imag ∈ [-30, 30]
            raw[2 * k + 1] = (sbyte)(((k * 13 + 11) % 59) - 29); // real ∈ [-29, 29]
        }
        return raw;
    }

    private static double[] BuildStftSeries()
    {
        var s = new double[SeriesLength];
        for (int n = 0; n < SeriesLength; n++)
            s[n] = ((n * 9 + 5) % 127) - 63; // integer-valued ∈ [-63, 63]
        return s;
    }

    [Fact]
    public void DumpGoldenFixture_AndSelfCheck()
    {
        sbyte[] raw = BuildRawIq();
        double[] series = BuildStftSeries();

        var amplitude = new float[Subcarriers];
        var phase = new float[Subcarriers];
        CsiDsp.Amplitude(raw, amplitude);
        CsiDsp.SanitizedPhase(raw, phase);

        float[,] spec = StftProcessor.Spectrogram(series);
        int frames = spec.GetLength(0);
        int bins = spec.GetLength(1);
        var stftFlat = new float[frames * bins];
        for (int f = 0; f < frames; f++)
            for (int m = 0; m < bins; m++)
                stftFlat[f * bins + m] = spec[f, m];

        // ── Self-consistency (the C# side of the gate) ──
        Assert.Equal(DspContract.Subcarriers, Subcarriers);
        Assert.Equal(5, frames); // (128-64)/16 + 1
        Assert.Equal(DspContract.StftBins, bins);
        Assert.All(amplitude, v => Assert.True(float.IsFinite(v)));
        Assert.All(phase, v => Assert.True(float.IsFinite(v)));
        Assert.All(stftFlat, v => Assert.True(float.IsFinite(v) && v >= 0));

        var golden = new GoldenFixture
        {
            Description = "V2 Phase 2 DSP golden fixture. Source of truth: CsiRadar.Backend. "
                + "Regenerated by DspGoldenParityTests; reproduced by wifi-csi-ml/tests/test_dsp_parity.py.",
            Subcarriers = Subcarriers,
            StftWindowSize = DspContract.StftWindowSize,
            StftHopSize = DspContract.StftHopSize,
            StftBins = DspContract.StftBins,
            StftFrames = frames,
            RawIq = Array.ConvertAll(raw, x => (int)x),
            StftSeries = Array.ConvertAll(series, x => (int)x),
            Amplitude = amplitude,
            SanitizedPhase = phase,
            Stft = stftFlat,
        };

        string dir = Path.Combine(FindRepoRoot(), "tools", "parity");
        Directory.CreateDirectory(dir);
        string path = Path.Combine(dir, "dsp_golden.json");
        File.WriteAllText(path, JsonSerializer.Serialize(golden, JsonOpts));

        Assert.True(File.Exists(path));
    }

    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    /// <summary>Walks up from the test assembly to the directory holding CsiRadar.slnx.</summary>
    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "CsiRadar.slnx")))
            dir = dir.Parent;
        Assert.NotNull(dir);
        return dir!.FullName;
    }

    private sealed class GoldenFixture
    {
        public string Description { get; init; } = "";
        public int Subcarriers { get; init; }
        public int StftWindowSize { get; init; }
        public int StftHopSize { get; init; }
        public int StftBins { get; init; }
        public int StftFrames { get; init; }
        public int[] RawIq { get; init; } = [];
        public int[] StftSeries { get; init; } = [];
        public float[] Amplitude { get; init; } = [];
        public float[] SanitizedPhase { get; init; } = [];
        public float[] Stft { get; init; } = [];
    }
}
