using System.Text.Json;
using CsiRadar.Backend.Application.Processing.Dsp;
using CsiRadar.Backend.Application.Processing.Windowing;
using CsiRadar.Backend.Core.Entities;
using Xunit;

namespace CsiRadar.Backend.Tests;

/// <summary>
/// Golden cross-language parity harness for the Phase 3 fused window (the mandatory gate,
/// exactly like <see cref="DspGoldenParityTests"/> — train/serve identity is the #1
/// invariant). The window <b>layout / axis order</b> is the thing most likely to diverge
/// silently, so this test exists to catch exactly that.
///
/// The backend is the source of truth: it builds a fully-deterministic aligned-DSP input
/// (integer raw I/Q per RX per frame → amplitude + sanitized phase via the proven
/// <see cref="CsiDsp"/>), feeds a full window through the real <see cref="WindowAssembler"/>,
/// and DUMPS the raw inputs + the fused dense/Doppler tensors to
/// <c>tools/parity/window_golden.json</c>. The Python windowing twin
/// (<c>wifi-csi-ml/tests/test_window_parity.py</c> + <c>src/window_twin.py</c>) reads that
/// same file, recomputes from the identical integer inputs, and asserts it reproduces the
/// SAME tensors within the shared 1e-4 tolerance. Integer inputs ⇒ no float-input
/// divergence; only the fusion/windowing transform + layout is under test.
/// </summary>
public class WindowGoldenParityTests
{
    private const int Wf = WindowContract.WindowFrames;
    private const int Rx = WindowContract.RxCount;
    private const int Sc = WindowContract.Subcarriers;
    private const uint StartSeq = 1000;

    /// <summary>
    /// Deterministic raw int8 I/Q for one (rx, frame): interleaved [imag, real] per
    /// subcarrier. Varies across rx, frame, and subcarrier so any transpose in the fused
    /// layout changes values and is caught. Mirrored exactly in window_twin.build_raw_iq.
    /// </summary>
    private static sbyte[] BuildRawIq(int rx, int frame)
    {
        var raw = new sbyte[2 * Sc];
        for (int k = 0; k < Sc; k++)
        {
            raw[2 * k] = (sbyte)(((rx * 31 + frame * 7 + k * 13 + 3) % 61) - 30);       // imag
            raw[2 * k + 1] = (sbyte)(((rx * 17 + frame * 5 + k * 11 + 7) % 59) - 29);   // real
        }
        return raw;
    }

    private static AlignedDspFrame BuildFrame(uint seq, int frame, int[] rawFlatSink, int rawStrideRx)
    {
        RxDsp Derive(int rx)
        {
            sbyte[] raw = BuildRawIq(rx, frame);
            // Record the raw ints into the golden sink in pinned order [rx, frame, iq].
            int baseIdx = rx * rawStrideRx + frame * (2 * Sc);
            for (int i = 0; i < raw.Length; i++)
                rawFlatSink[baseIdx + i] = raw[i];

            var amp = new float[Sc];
            var phase = new float[Sc];
            CsiDsp.Amplitude(raw, amp);
            CsiDsp.SanitizedPhase(raw, phase);
            return new RxDsp { Amplitude = amp, SanitizedPhase = phase };
        }

        var dummyRx = new CsiData { RawCsiData = [], RawDataLength = 0 };
        return new AlignedDspFrame
        {
            SeqNo = seq,
            Rx0 = Derive(0),
            Rx1 = Derive(1),
            Source = new AlignedCsiFrame { SeqNo = seq, Rx0 = dummyRx, Rx1 = dummyRx },
        };
    }

    [Fact]
    public void DumpGoldenFixture_AndSelfCheck()
    {
        int rawStrideRx = Wf * (2 * Sc);
        var rawFlat = new int[Rx * rawStrideRx];

        var assembler = new WindowAssembler();
        FusedWindow? window = null;

        for (int f = 0; f < Wf; f++)
        {
            var frame = BuildFrame(StartSeq + (uint)f, f, rawFlat, rawStrideRx);
            var result = assembler.Accept(frame);
            if (result.Emitted is not null)
            {
                // Exactly one window, and only on the final frame of the first full window.
                Assert.Null(window);
                Assert.Equal(Wf - 1, f);
                window = result.Emitted;
            }
        }

        Assert.NotNull(window);

        // ── Self-consistency (the C# side of the gate) ──
        Assert.Equal(13, WindowContract.StftFrames);
        Assert.Equal(WindowContract.DenseLength, window!.Dense.Length);
        Assert.Equal(WindowContract.DopplerLength, window.Doppler.Length);
        Assert.Equal(StartSeq, window.StartSeqNo);
        Assert.Equal(StartSeq + (uint)(Wf - 1), window.EndSeqNo);
        Assert.All(window.Dense, v => Assert.True(float.IsFinite(v)));
        Assert.All(window.Doppler, v => Assert.True(float.IsFinite(v) && v >= 0));

        var golden = new GoldenFixture
        {
            Description = "V2 Phase 3 fused-window golden fixture. Source of truth: CsiRadar.Backend. "
                + "Regenerated by WindowGoldenParityTests; reproduced by "
                + "wifi-csi-ml/tests/test_window_parity.py. Raw I/Q order [rx, frame, iq]; "
                + "dense [rx, modality, frame, subcarrier]; doppler [rx, subcarrier, stftFrame, bin].",
            RxCount = Rx,
            Modalities = WindowContract.Modalities,
            Subcarriers = Sc,
            WindowFrames = Wf,
            WindowSlide = WindowContract.WindowSlide,
            StftWindowSize = DspContract.StftWindowSize,
            StftHopSize = DspContract.StftHopSize,
            StftFrames = WindowContract.StftFrames,
            StftBins = WindowContract.StftBins,
            StartSeqNo = window.StartSeqNo,
            EndSeqNo = window.EndSeqNo,
            DenseShape = [Rx, WindowContract.Modalities, Wf, Sc],
            DopplerShape = [Rx, Sc, WindowContract.StftFrames, WindowContract.StftBins],
            RawIq = rawFlat,
            Dense = window.Dense,
            Doppler = window.Doppler,
        };

        string dir = Path.Combine(FindRepoRoot(), "tools", "parity");
        Directory.CreateDirectory(dir);
        string path = Path.Combine(dir, "window_golden.json");
        // Compact (not indented): the fixture is large (~120k floats); readability is not
        // a goal for a machine-checked golden.
        File.WriteAllText(path, JsonSerializer.Serialize(golden, JsonOpts));

        Assert.True(File.Exists(path));
    }

    private static readonly JsonSerializerOptions JsonOpts = new()
    {
        WriteIndented = false,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    /// <summary>Walks up from the test assembly to the directory holding CsiRadar.slnx.</summary>
    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "CsiRadar.slnx")))
            dir = dir.Parent;
        Assert.NotNull(dir);
        return dir!.FullName;
    }

    private sealed class GoldenFixture
    {
        public string Description { get; init; } = "";
        public int RxCount { get; init; }
        public int Modalities { get; init; }
        public int Subcarriers { get; init; }
        public int WindowFrames { get; init; }
        public int WindowSlide { get; init; }
        public int StftWindowSize { get; init; }
        public int StftHopSize { get; init; }
        public int StftFrames { get; init; }
        public int StftBins { get; init; }
        public uint StartSeqNo { get; init; }
        public uint EndSeqNo { get; init; }
        public int[] DenseShape { get; init; } = [];
        public int[] DopplerShape { get; init; } = [];
        public int[] RawIq { get; init; } = [];
        public float[] Dense { get; init; } = [];
        public float[] Doppler { get; init; } = [];
    }
}
